resources:
- k8s-specifications/db-deployment.yaml
- k8s-specifications/db-service.yaml

- k8s-specifications/redis-deployment.yaml
- k8s-specifications/redis-service.yaml
- k8s-specifications/result-deployment.yaml
- k8s-specifications/result-service.yaml
- k8s-specifications/vote-deployment.yaml
- k8s-specifications/vote-namespace.yml
- k8s-specifications/vote-service.yaml
- k8s-specifications/worker-deployment.yaml
